  - name: Create Index Html
    template: src=index.html.j2 dest={{ nginx_web_dir }}/html/index.html owner={{ nginx_user }} group={{ nginx_user }} mode=0644

  - name: Copy Nginx Start Script
    template: src=nginx.j2 dest=/etc/init.d/nginx owner=root group=root mode=0755

  - name: Copy Nginx Config
    template: src=nginx.conf.j2 dest={{nginx_web_dir}}/nginx.conf owner=root group=root mode=0644

  - name: Copy Nginx Vhost Config
    template: src=vhost.conf.j2 dest={{nginx_web_dir}}/conf.d/vhost.conf owner=root group=root mode=0644

  - name: Start Nginx Service
    service: name=nginx state=restarted

  - name: Add Boot Start Nginx Service
    shell: chkconfig   nginx on
